require_relative 'transform/base'
require_relative 'transform/solr/json_edismax'
require_relative 'transform/solr/local_params'
require_relative 'transform/solr/solr_search'
require_relative 'transform/solr/utilities'