# frozen_string_literal: true

class TestDocs
  DOCS = [
    {id: 1, author_t: "huck finn"},
    {id: 2, title_t: "A Story", author_t: "Search Dude"},
    {id: 3, title_t: "Entirely Unrelated", author_t: "Some Dude"},
    {id: 4, title_t: "author finn", author_t: "huck sawyer"},
    {id: 5, title_t: "blah", callnum_t: "some book"},
    {id: 6, title_t: "book one", author_t: "person one"},
    {id: 7, title_t: "book one:author one"},
    {id: 8, title_t: "collected stories", author_t: "mark twain", subject_t: "huck finn"},
    {id: 9, title_t: "collected stories", author_t: "mark twain", subject_t: "huck finn, tom sawyer"},
    {id: 10, title_t: "collected stories", author_t: "mark twain"},
    {id: 11, title_t: "huck finn : or, a river story", author_t: "mark twain"},
    {id: 12, title_t: "huck finn and tom sawyer: works of mark twain", author_t: "Some Person"},
    {id: 13, title_t: "huck finn", author_t: "mark twain"},
    {id: 14, title_t: "huck finn", author_t: "mark twain, samuel clemens"},
    {id: 15, title_t: "huck finn", author_t: "samuel clemens"},
    {id: 16, title_t: "huck finn", author_t: "some person"},
    {id: 17, title_t: "huck finn", author_t: "someone random"},
    {id: 18, title_t: "huck finn", subject_t: "pseudonymous author_t: mark twain"},
    {id: 19, title_t: "huck finn"},
    {id: 20, title_t: "huck finn, tom sawyer"},
    {id: 21, title_t: "huck sawyer"},
    {id: 22, title_t: "huckleberry finn"},
    {id: 23, title_t: "mark twain was samuel clemens", author_t: "some person"},
    {id: 24, title_t: "mark twain", author_t: "huck finn"},
    {id: 25, title_t: "mark twin and huck fain"},
    {id: 26, title_t: "my adjectival name", author_t: "bill somebody"},
    {id: 27, title_t: "my name", author_t: "bill somebody"},
    {id: 28, title_t: "not huck finn", author_t: "mark twain"},
    {id: 29, title_t: "not tom sawyer", author_t: "mark twain"},
    {id: 30, title_t: "one bill on capitol hill", author_t: "two politicians"},
    {id: 31, title_t: "one book", author_t: "two people"},
    {id: 32, title_t: "some book", callnum_t: "blah"},
    {id: 33, title_t: "somebody"},
    {id: 34, title_t: "something random:huck finn"},
    {id: 35, title_t: "something"},
    {id: 36, title_t: "three things about five", author_t: "two of one"},
    {id: 37, title_t: "tom finn"},
    {id: 38, title_t: "tom sawyer", author_t: "mark twain AKA samuel clemens"},
    {id: 39, title_t: "tom sawyer", author_t: "mark twain"},
    {id: 40, title_t: "tom sawyer", author_t: "samuel clemens"},
    {id: 41, title_t: "tom sawyer"},
    {id: 42, title_t: "twain and clemens", author_t: "mark person"},
    {id: 43, title_t: "two bills on capitol hill", author_t: "one politician"},
    {id: 44, title_t: "two things about one", author_t: "five of eight", subject_t: "one, four, three"},
    {id: 45, title_t: "two things", author_t: "bill one somebody"}
  ].freeze
end
